CREATE TABLE IF NOT EXISTS loan (
    id CHAR(36) PRIMARY KEY,
    customer JSON NOT NULL,
    status VARCHAR(30) NOT NULL,
    version INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);