version: '3.8'

services:
  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/opt/application/src
      - ./cache:/opt/application/cache:z
      - ./gradle:/opt/application/gradle
      - ./gradlew:/opt/application/gradlew
      - ./gradle.properties:/opt/application/gradle.properties
      - ./build.gradle.kts:/opt/application/build.gradle.kts
      - ./settings.gradle.kts:/opt/application/settings.gradle.kts
    ports:
      - "8080:8080"
    env_file:
      - ./environment/local.env
    networks:
      - app

networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.47.0.0/16"
          gateway: "172.47.0.1"