version: '3.8'

services:
  quarkus-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
    container_name: loan-app
    volumes:
      - ./src:/opt/application/src
      - ./cache:/opt/application/cache:z
      - ./gradle:/opt/application/gradle
      - ./gradlew:/opt/application/gradlew
      - ./gradle.properties:/opt/application/gradle.properties
      - ./build.gradle.kts:/opt/application/build.gradle.kts
      - ./settings.gradle.kts:/opt/application/settings.gradle.kts
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - ./environment/local.env
    networks:
      - loan_app

  # Kafka em modo KRaft (sem Zookeeper)
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CLUSTER_ID=RaNdOmClUsTeRiD123456789
      - CLUSTER_ID=RaNdOmClUsTeRiD123456789
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
    volumes:
      - /var/lib/kafka/data
    networks:
      - loan_app

  # Kafka Connect com JDBC Source Connector
  kafka-connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: kafka-connect
    depends_on:
      - kafka
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: "kafka-connect-group"
      CONNECT_CONFIG_STORAGE_TOPIC: "__connect-configs"
      CONNECT_OFFSET_STORAGE_TOPIC: "__connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "__connect-status"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
      CONNECT_JDBC_DRIVER_PATH: "/usr/share/java/kafka-connect-jdbc"
      CONNECT_PRODUCER_MAX_REQUEST_SIZE: 10485760
    ports:
      - "8083:8083"
    volumes:
      - ./kafka-connect/jars:/usr/share/java/kafka-connect-jdbc
    networks:
      - loan_app

  control-center:
    image: confluentinc/cp-enterprise-control-center:latest
    container_name: control-center
    environment:
      - CONTROL_CENTER_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - CONTROL_CENTER_CONNECT_CLUSTER=kafka-connect:8083
#      - CONTROL_CENTER_ZOOKEEPER_CONNECT=zookeeper:2181  # Se você estiver usando Zookeeper
      - CONTROL_CENTER_KAFKA_CLUSTER=kafka
      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:9092
      - CONTROL_CENTER_REPLICATION_FACTOR=1
    ports:
      - "9021:9021"
    depends_on:
      - kafka
      - kafka-connect
    networks:
      - loan_app

  mysql:
    image: mysql:latest
    container_name: loan-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: loan
      MYSQL_USER: loan
      MYSQL_PASSWORD: loan
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
    networks:
      - loan_app

networks:
  loan_app:
    external:
      name: loan_app